# Generated by Django 4.1.7 on 2023-02-18 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emscore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdetails',
            name='time',
            field=models.DateTimeField(),
        ),
    ]
