# Generated by Django 4.1.7 on 2023-02-21 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emscore', '0003_eventdetails_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventdetails',
            name='attendants',
            field=models.ManyToManyField(related_name='useds_attendant_event', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='eventdetails',
            name='booked_by',
            field=models.ManyToManyField(related_name='users_booked_event', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='eventdetails',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='event_author', to=settings.AUTH_USER_MODEL),
        ),
    ]
