# Generated by Django 4.1.7 on 2023-02-22 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emscore', '0004_eventdetails_attendants_eventdetails_booked_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionDb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('subscribed_by', models.ManyToManyField(related_name='users_subscribed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
